services:
  - type: web
    name: kyc-backend
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py migrate"
    startCommand: "cd backend && gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: "False"

